import type { CustomBiome } from '../types/map';

export const DEFAULT_BIOMES: CustomBiome[] = [
  {
    id: 'deep_ocean',
    name: 'Derin Okyanus',
    color: '#0f172a',
    borderColor: '#1e293b',
    movementCost: 99,
    minElevation: 0,
    maxElevation: 0.22,
    minTemperature: 0,
    maxTemperature: 1,
    minHumidity: 0,
    maxHumidity: 1,
    iconName: 'Waves',
  },
  {
    id: 'shallow_water',
    name: 'Sığ Deniz',
    color: '#0284c7',
    borderColor: '#0369a1',
    movementCost: 3,
    minElevation: 0.22,
    maxElevation: 0.32,
    minTemperature: 0,
    maxTemperature: 1,
    minHumidity: 0,
    maxHumidity: 1,
    iconName: 'Waves',
  },
  {
    id: 'sand_beach',
    name: 'Kumsal / Çöl',
    color: '#fde047',
    borderColor: '#eab308',
    movementCost: 1.5,
    minElevation: 0.32,
    maxElevation: 0.8,
    minTemperature: 0.6,
    maxTemperature: 1.0,
    minHumidity: 0,
    maxHumidity: 0.3,
    iconName: 'Sun',
  },
  {
    id: 'tundra_snow',
    name: 'Karlı Tundra',
    color: '#e2e8f0',
    borderColor: '#cbd5e1',
    movementCost: 2,
    minElevation: 0.32,
    maxElevation: 0.8,
    minTemperature: 0,
    maxTemperature: 0.25,
    minHumidity: 0,
    maxHumidity: 1,
    iconName: 'Snowflake',
  },
  {
    id: 'grassland',
    name: 'Otluk / Ova',
    color: '#84cc16',
    borderColor: '#65a30d',
    movementCost: 1,
    minElevation: 0.32,
    maxElevation: 0.6,
    minTemperature: 0.25,
    maxTemperature: 0.75,
    minHumidity: 0.2,
    maxHumidity: 0.7,
    iconName: 'Trees',
  },
  {
    id: 'forest',
    name: 'Yoğun Orman',
    color: '#15803d',
    borderColor: '#166534',
    movementCost: 1.5,
    minElevation: 0.32,
    maxElevation: 0.7,
    minTemperature: 0.25,
    maxTemperature: 0.7,
    minHumidity: 0.6,
    maxHumidity: 1.0,
    iconName: 'Trees',
  },
  {
    id: 'swamp',
    name: 'Bataklık',
    color: '#3f6212',
    borderColor: '#365314',
    movementCost: 2.5,
    minElevation: 0.32,
    maxElevation: 0.45,
    minTemperature: 0.4,
    maxTemperature: 0.9,
    minHumidity: 0.75,
    maxHumidity: 1.0,
    iconName: 'Droplets',
  },
  {
    id: 'hills',
    name: 'Tepelik',
    color: '#b45309',
    borderColor: '#92400e',
    movementCost: 2,
    minElevation: 0.6,
    maxElevation: 0.8,
    minTemperature: 0.15,
    maxTemperature: 0.85,
    minHumidity: 0,
    maxHumidity: 1,
    iconName: 'Mountain',
  },
  {
    id: 'high_mountains',
    name: 'Yüksek Dağlar',
    color: '#475569',
    borderColor: '#334155',
    movementCost: 5,
    minElevation: 0.8,
    maxElevation: 1.0,
    minTemperature: 0,
    maxTemperature: 1,
    minHumidity: 0,
    maxHumidity: 1,
    iconName: 'MountainSnow',
  },
];
